
sudo: required  # izinlere ihtiyacı var

services:
  - docker

before_install:
  - docker build -t test -f Dockerfile.dev .   # test için conteynır oluşuturulur.

# travis komutları çalıştırı ve çıktıını izler hata varsa testler düzgün çalışmadı kodda hata var.
scripts:
  - docker run -e CI=true test npm run test
